INSERT INTO web_regioneschile (nombre) VALUES
    ('Arica y Parinacota'),
    ('Tarapacá'),
    ('Antofagasta'),
    ('Atacama'),
    ('Coquimbo'),
    ('Valparaíso'),
    ('Metropolitana de Santiago'),
    ('Libertador General Bernardo O''Higgins'),
    ('Maule'),
    ('Ñuble'),
    ('Biobío'),
    ('Araucanía'),
    ('Los Ríos'),
    ('Los Lagos'),
    ('Aysén del General Carlos Ibáñez del Campo'),
    ('Magallanes y de la Antártica Chilena');