# Generated by Django 5.0.4 on 2024-05-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('Nombre_1', models.CharField(max_length=50)),
                ('Nombre_2', models.CharField(max_length=50)),
                ('Apellido_1', models.CharField(max_length=50)),
                ('Apellido_2', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=9)),
                ('tipo_de_usuario', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
