# Generated by Django 5.0.4 on 2024-05-10 23:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_form_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=10, null=True)),
                ('depto', models.CharField(max_length=50, null=True)),
                ('comuna', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegionesChile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('m2_construidos', models.IntegerField()),
                ('m2_totales', models.IntegerField()),
                ('estacionamientos', models.IntegerField()),
                ('cantidad_habitaciones', models.IntegerField()),
                ('cantidad_banos', models.IntegerField()),
                ('tipo_de_inmueble', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('parcela', 'Parcela')], default='Casa', max_length=20)),
                ('precio_arriendo', models.IntegerField()),
                ('estado', models.BooleanField(choices=[('disponible', 'Disponible'), ('no disponible', 'No disponible')], default=True)),
                ('direccion', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='ExtendUsuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='RUT')),
                ('nombre_1', models.CharField(max_length=50, verbose_name='Nombre_1')),
                ('nombre_2', models.CharField(max_length=50, verbose_name='Nombre_2')),
                ('apellido_1', models.CharField(max_length=50, verbose_name='Apellido_1')),
                ('apellido_2', models.CharField(max_length=50, verbose_name='Apellido_2')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('tipo_usuario', models.CharField(choices=[('arrendador', 'Arrendador'), ('arrendatario', 'Arrendatario')], default='Arrendatario', max_length=20, verbose_name='Tipo_usuario')),
                ('direccion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.direccion', verbose_name='Direccion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('inmuebles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.inmueble', verbose_name='Inmuebles')),
            ],
        ),
        migrations.CreateModel(
            name='ComunasChile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.regioneschile')),
            ],
        ),
    ]
