# Generated by Django 5.0.4 on 2024-05-10 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='region',
        ),
        migrations.AlterField(
            model_name='direccion',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.comunaschile'),
        ),
    ]
