# Generated by Django 5.0.4 on 2024-05-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_direccion_ciudad_remove_direccion_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media/inmuebles/'),
        ),
    ]
