# Generated by Django 5.0.4 on 2024-05-05 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_usuario_direccion_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('m2_construidos', models.IntegerField()),
                ('m2_totales', models.IntegerField()),
                ('estacionamientos', models.IntegerField()),
                ('cantidad_habitaciones', models.IntegerField()),
                ('cantidad_banos', models.IntegerField()),
                ('tipo_de_inmueble', models.CharField(max_length=50)),
                ('precio_arriendo', models.IntegerField()),
            ],
            options={
                'db_table': 'inmueble',
            },
        ),
        migrations.AddField(
            model_name='direccion',
            name='inmueble',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.inmueble'),
        ),
    ]
