# Generated by Django 5.0.4 on 2024-05-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_usuario_options_remove_usuario_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
