# Generated by Django 5.0.4 on 2024-05-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_inmueble_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='estado',
            field=models.BooleanField(choices=[(True, 'Disponible'), (False, 'No disponible')], default=False),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/inmuebles/'),
        ),
    ]
