# Generated by Django 5.0.4 on 2024-05-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
