# Generated by Django 5.0.4 on 2024-05-05 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_inmueble_direccion_inmueble'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='inmueble',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='direccion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.direccion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.direccion'),
        ),
    ]
