# Generated by Django 5.0.4 on 2024-05-08 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_inmueble_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='inmuebles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.inmueble'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='estado',
            field=models.BooleanField(choices=[('disponible', 'Disponible'), ('no disponible', 'No disponible')], default=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_de_inmueble',
            field=models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('parcela', 'Parcela')], default='Casa', max_length=20),
        ),
    ]
