# Generated by Django 5.0.4 on 2024-05-14 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_inmueble_estado_alter_inmueble_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='imagen',
            new_name='imagenes',
        ),
    ]
