# Generated by Django 5.0.4 on 2024-05-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_usuario_inmuebles_alter_inmueble_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='rut',
            field=models.CharField(default='15337297-7', max_length=12, unique=True, verbose_name='RUT'),
            preserve_default=False,
        ),
    ]
