# Generated by Django 5.0.4 on 2024-05-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_usuario_rut'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inmueble',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
