# Generated by Django 5.0.4 on 2024-05-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_inmueble_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
