# Generated by Django 5.0.4 on 2024-05-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_contactform_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='rut',
            field=models.CharField(max_length=12, verbose_name='RUT'),
        ),
    ]
