# Generated by Django 5.0.4 on 2024-05-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_inmueble_table_alter_usuario_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_de_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('arrendador', 'Arrendador'), ('arrendatario', 'Arrendatario')], default='Arrendatario', max_length=20),
        ),
    ]
