# Generated by Django 5.0.4 on 2024-05-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_contactform_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='RUT'),
        ),
    ]
