# Generated by Django 5.0.4 on 2024-05-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_inmueble_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendusuario',
            name='inmuebles',
        ),
        migrations.AddField(
            model_name='extendusuario',
            name='inmuebles_arrendados',
            field=models.ManyToManyField(blank=True, to='web.inmueble', verbose_name='Inmuebles Arrendados'),
        ),
    ]
