# Generated by Django 5.0.4 on 2024-05-08 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_contactform_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='rut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.usuario'),
        ),
    ]
