# Generated by Django 5.0.4 on 2024-05-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_extendusuario_inmuebles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendusuario',
            name='inmuebles_publicados',
            field=models.ManyToManyField(blank=True, related_name='inmuebles_publicados', to='web.inmueble', verbose_name='Inmuebles Publicados'),
        ),
        migrations.AlterField(
            model_name='extendusuario',
            name='inmuebles_arrendados',
            field=models.ManyToManyField(blank=True, related_name='inmuebles_arrendados', to='web.inmueble', verbose_name='Inmuebles Arrendados'),
        ),
    ]
