# Generated by Django 5.0.4 on 2024-05-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_extendusuario_inmuebles_publicados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to='arrienda_rural/front/assets/media/inmuebles'),
        ),
    ]
